import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { TabProvider } from "@/context/TabContext";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Multimedia Editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <TabProvider>
          {children}
        </TabProvider>
      </body>
    </html>
  );
}
